const express = require("express");
const { staticWebContentsCont } = require("../controllers");
const mids = require("../controllers/middlewares");
const { User } = require("../entities");

const staticWebContentsRouter = express.Router();
staticWebContentsRouter.get("/", staticWebContentsCont.get);
staticWebContentsRouter.use(mids.forceAccessToken([User.userTypes.Admin]));
staticWebContentsRouter.put("/logo-image", staticWebContentsCont.updateLogoImage);
staticWebContentsRouter.put("/hero", staticWebContentsCont.updateHero);
staticWebContentsRouter.put("/about-us-image", staticWebContentsCont.updateAboutUsImage);
staticWebContentsRouter.put("/why-us", staticWebContentsCont.updateWhyUs);
staticWebContentsRouter.put("/what-makes-us-unique", staticWebContentsCont.updateWhatMakesUsUnique);
staticWebContentsRouter.put("/who-are-we", staticWebContentsCont.updateWhoAreWe);
staticWebContentsRouter.put("/how-tos", staticWebContentsCont.updateHowTos);
staticWebContentsRouter.post("/brands", staticWebContentsCont.addBrand);
staticWebContentsRouter.patch("/brands/:id", staticWebContentsCont.updateBrand);
staticWebContentsRouter.delete("/brands/:id", staticWebContentsCont.deleteBrand);
staticWebContentsRouter.post("/social-links", staticWebContentsCont.addSocialLink);
staticWebContentsRouter.patch("/social-links/:id", staticWebContentsCont.updateSocialLink);
staticWebContentsRouter.delete("/social-links/:id", staticWebContentsCont.deleteSocialLink);
module.exports = staticWebContentsRouter;